development:
  adapter: postgresql
  encoding: unicode
  database: sample_development
  username: postgres
  password: qburst
  host: localhost
  port: 5432

production:
  adapter: postgresql
  encoding: unicode
  database: sample_development
  username: postgres
  password: qburst
  host: localhost
  port: 5432

test:
  adapter: postgresql
  encoding: unicode
  database: sample_development
  username: postgres
  password: qburst
  host: localhost
  port: 5432